### ISSUE TITLE
[Feature] Add Icons

### ISSUE THREAD

**Issue by liblaf** [liblaf/sub-converter#80]
### 🥰 Feature Description

```yaml
proxy-groups:
  - name: PROXY
    icon: https://api.liblaf.me/icons/Proxy.png
```

### 🧐 Proposed Solution

- <https://flagcdn.com/>
- <https://github.com/Koolson/Qure/tree/master/IconSet/Color>
- <https://wiki.metacubex.one/config/proxy-groups/#icon>
